# Generated by Django 2.2.1 on 2019-09-03 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baike',
            name='pubtime',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='market',
            name='pubtime',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='price',
            name='pubtime',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='pubtime',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='statute',
            name='pubtime',
            field=models.DateField(),
        ),
    ]
