# Generated by Django 2.2.1 on 2019-09-04 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20190903_2103'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='baike',
            options={'ordering': ['-pubtime'], 'verbose_name': '农业百科', 'verbose_name_plural': '农业百科'},
        ),
        migrations.AlterModelOptions(
            name='market',
            options={'ordering': ['-pubtime'], 'verbose_name': '市场动态', 'verbose_name_plural': '市场动态'},
        ),
        migrations.AlterModelOptions(
            name='price',
            options={'ordering': ['-pubtime'], 'verbose_name': '价格行情', 'verbose_name_plural': '价格行情'},
        ),
        migrations.AlterModelOptions(
            name='purchase',
            options={'ordering': ['-pubtime'], 'verbose_name': '求购信息', 'verbose_name_plural': '求购信息'},
        ),
        migrations.AlterModelOptions(
            name='statute',
            options={'ordering': ['-pubtime'], 'verbose_name': '政策法规', 'verbose_name_plural': '政策法规'},
        ),
        migrations.AlterModelOptions(
            name='userinfo',
            options={'ordering': ['-c_time'], 'verbose_name': '用户列表', 'verbose_name_plural': '用户列表'},
        ),
        migrations.AlterField(
            model_name='baike',
            name='author',
            field=models.CharField(blank=True, max_length=30, verbose_name='作者'),
        ),
        migrations.AlterField(
            model_name='baike',
            name='content',
            field=models.TextField(verbose_name='文章'),
        ),
        migrations.AlterField(
            model_name='baike',
            name='pubtime',
            field=models.DateField(verbose_name='发布日期'),
        ),
        migrations.AlterField(
            model_name='baike',
            name='source',
            field=models.CharField(max_length=30, verbose_name='来源'),
        ),
        migrations.AlterField(
            model_name='baike',
            name='title',
            field=models.CharField(max_length=30, verbose_name='标题'),
        ),
        migrations.AlterField(
            model_name='market',
            name='author',
            field=models.CharField(blank=True, max_length=30, verbose_name='作者'),
        ),
        migrations.AlterField(
            model_name='market',
            name='content',
            field=models.TextField(verbose_name='文章'),
        ),
        migrations.AlterField(
            model_name='market',
            name='pubtime',
            field=models.DateField(verbose_name='发布日期'),
        ),
        migrations.AlterField(
            model_name='market',
            name='source',
            field=models.CharField(max_length=30, verbose_name='来源'),
        ),
        migrations.AlterField(
            model_name='market',
            name='title',
            field=models.CharField(max_length=30, verbose_name='标题'),
        ),
        migrations.AlterField(
            model_name='price',
            name='author',
            field=models.CharField(blank=True, max_length=30, verbose_name='作者'),
        ),
        migrations.AlterField(
            model_name='price',
            name='content',
            field=models.TextField(verbose_name='文章'),
        ),
        migrations.AlterField(
            model_name='price',
            name='pubtime',
            field=models.DateField(verbose_name='发布日期'),
        ),
        migrations.AlterField(
            model_name='price',
            name='source',
            field=models.CharField(max_length=30, verbose_name='来源'),
        ),
        migrations.AlterField(
            model_name='price',
            name='title',
            field=models.CharField(max_length=30, verbose_name='标题'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='address',
            field=models.CharField(max_length=30, verbose_name='详细地址'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='category',
            field=models.CharField(max_length=30, verbose_name='种类归类'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='detail',
            field=models.TextField(verbose_name='详细描述'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='price',
            field=models.CharField(max_length=20, verbose_name='最新报价'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='pubtime',
            field=models.DateField(auto_now_add=True, verbose_name='发布日期'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='region',
            field=models.CharField(max_length=50, verbose_name='地区'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='title',
            field=models.CharField(max_length=30, verbose_name='标题'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='views',
            field=models.PositiveIntegerField(default=0, verbose_name='浏览量'),
        ),
        migrations.AlterField(
            model_name='statute',
            name='author',
            field=models.CharField(blank=True, max_length=30, verbose_name='作者'),
        ),
        migrations.AlterField(
            model_name='statute',
            name='content',
            field=models.TextField(verbose_name='文章'),
        ),
        migrations.AlterField(
            model_name='statute',
            name='pubtime',
            field=models.DateField(verbose_name='发布日期'),
        ),
        migrations.AlterField(
            model_name='statute',
            name='source',
            field=models.CharField(max_length=30, verbose_name='来源'),
        ),
        migrations.AlterField(
            model_name='statute',
            name='title',
            field=models.CharField(max_length=30, verbose_name='标题'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='c_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='邮箱'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='name',
            field=models.CharField(max_length=20, unique=True, verbose_name='用户名'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='password',
            field=models.CharField(max_length=128, verbose_name='密码'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='phone',
            field=models.CharField(max_length=11, unique=True, verbose_name='手机号'),
        ),
    ]
