# Generated by Django 2.2.1 on 2019-09-06 15:44

from django.db import migrations
import mdeditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20190904_2035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='content',
            field=mdeditor.fields.MDTextField(verbose_name='文章'),
        ),
    ]
