# Generated by Django 2.2.1 on 2019-09-10 08:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_auto_20190906_1544'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='regiontext',
            field=models.ManyToManyField(to='product.AreaInfo'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='category',
            field=models.CharField(max_length=30, verbose_name='产品品种'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='purchases',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.UserInfo', verbose_name='用户'),
        ),
    ]
