# Generated by Django 2.2.1 on 2019-09-10 08:29

from django.db import migrations, models
import django.db.models.deletion
import product.models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_auto_20190910_0803'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='regiontext',
        ),
        migrations.AddField(
            model_name='purchase',
            name='purcate',
            field=models.ManyToManyField(to='product.Category', verbose_name='品种筛选'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='purregion',
            field=models.ManyToManyField(to='product.AreaInfo', verbose_name='地区筛选'),
        ),
        migrations.CreateModel(
            name='Supply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='标题')),
                ('price', models.CharField(max_length=20, verbose_name='最新报价')),
                ('pubtime', models.DateField(auto_now_add=True, verbose_name='发布时间')),
                ('region', models.CharField(max_length=50, verbose_name='地区')),
                ('address', models.CharField(max_length=30, verbose_name='详细地址')),
                ('views', models.PositiveIntegerField(default=0, verbose_name='浏览量')),
                ('category', models.CharField(max_length=30, verbose_name='产品品种')),
                ('detail', models.TextField(verbose_name='详细描述')),
                ('img', models.ImageField(null=True, upload_to='', verbose_name=product.models.image_upload_to)),
                ('supcate', models.ManyToManyField(to='product.Category', verbose_name='品种筛选')),
                ('supplys', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.UserInfo', verbose_name='用户')),
                ('supregion', models.ManyToManyField(to='product.AreaInfo', verbose_name='地区筛选')),
            ],
        ),
    ]
