# Generated by Django 2.2.1 on 2019-09-10 22:07

from django.db import migrations, models
import product.models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_auto_20190910_0829'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='supply',
            options={'ordering': ['-pubtime'], 'verbose_name': '供应信息', 'verbose_name_plural': '供应信息'},
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='price',
        ),
        migrations.AlterField(
            model_name='purchase',
            name='category',
            field=models.CharField(max_length=30, verbose_name='产品类别'),
        ),
        migrations.AlterField(
            model_name='supply',
            name='category',
            field=models.CharField(max_length=30, verbose_name='产品类别'),
        ),
        migrations.AlterField(
            model_name='supply',
            name='img',
            field=models.ImageField(null=True, upload_to=product.models.image_upload_to),
        ),
    ]
