# Generated by Django 2.2.1 on 2019-12-02 19:15

from django.db import migrations, models
import product.models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_auto_20190910_2207'),
    ]

    operations = [
        migrations.CreateModel(
            name='Storage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=10, verbose_name='仓库类型')),
                ('pubtime', models.DateField(verbose_name='发布日期')),
                ('address', models.CharField(max_length=30, verbose_name='所在城市')),
                ('area', models.CharField(max_length=30, verbose_name='仓库面积')),
                ('price', models.TextField(max_length=30, verbose_name='每间价格')),
            ],
            options={
                'verbose_name': '仓储信息',
                'verbose_name_plural': '仓储信息',
                'ordering': ['-pubtime'],
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=30, verbose_name='车牌号')),
                ('type', models.CharField(max_length=10, verbose_name='类型')),
                ('load', models.CharField(max_length=30, verbose_name='载重')),
                ('address', models.CharField(max_length=30, verbose_name='所在城市')),
                ('people', models.CharField(max_length=30, verbose_name='联系人')),
                ('phone', models.CharField(max_length=30, verbose_name='联系电话')),
                ('pubtime', models.DateField(verbose_name='发布日期')),
            ],
            options={
                'verbose_name': '车源信息',
                'verbose_name_plural': '车源信息',
                'ordering': ['-pubtime'],
            },
        ),
        migrations.AlterField(
            model_name='supply',
            name='img',
            field=models.ImageField(null=True, upload_to=product.models.image_upload_to, verbose_name='图片'),
        ),
    ]
