# Generated by Django 2.2.1 on 2019-12-02 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_auto_20191202_1915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storage',
            name='price',
            field=models.CharField(max_length=30, verbose_name='每间价格'),
        ),
    ]
